# Deploys apps to the docs/ directory, which is the directory from which
# the Pages website is served.
name: Deploy apps

on:
  # Allow manual trigger from the Actions tab:
  # https://github.com/Automattic/a8c-matrix-element/actions/workflows/fetch.yml
  workflow_dispatch:

  # Trigger when versions files change
  push:
    paths:
      - 'latest-versions/*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # The ACCESS_TOKEN secret is defined at
          # https://github.com/Automattic/a8c-matrix-element/settings/secrets/actions
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Clear docs/ directory
        run: rm -rf docs && mkdir docs

      - name: Extract release into docs/ directory
        run: |
          tar xvz -f ${{ env.ELEMENT_TAR_NAME }} -C docs --strip-components=1 && \
          rm ${{ env.ELEMENT_TAR_NAME }}

      - name: Remove sample config
        run: rm docs/config.sample.json

      - name: Install custom files from public/ directory
        run: cp -R public/* docs/

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")

      - name: Commit release
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Team Orbit'
          git config --global user.email 'orbit-matrix@automattic.com'
          git add .
          git commit -m "Release ${{ env.ELEMENT_VERSION }}"
          git push
