# Writes latest element-web version in the latest-version/version file.

name: Discover latest version of element-web

on:
  # Trigger every Sunday at 08:00
  schedule:
    - cron: '0 0 * * 0'

  # Allow manual trigger from the Actions tab
  workflow_dispatch:

jobs:
  get-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # ACCESS_TOKEN is defined at https://github.com/Automattic/a8c-matrix-element/settings/secrets/actions
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Discover latest version
        run: |
          curl -sL https://api.github.com/repos/vector-im/element-web/releases/latest | \
          jq -r ".tag_name" > latest-version/version

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")

      - name: Assign version to environment variable
        if: steps.git-check.outputs.modified == 'true'
        run: echo 'ELEMENT_VERSION='$(cat latest-version/version) >> $GITHUB_ENV

      - name: Commit latest version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Team Orbit'
          git config --global user.email 'orbit-matrix@automattic.com'
          git add .
          git commit -m "Set latest version to ${{ env.ELEMENT_VERSION }}"
          git push
