# Writes the latest version of all apps in files under latest-versions/.
name: Discover latest versions of apps

on:
  # Allow manual trigger from the Actions tab:
  # https://github.com/Automattic/chat.a8c.com/actions/workflows/latest-versions.yml
  workflow_dispatch:

  # Trigger every Sunday at 08:00
  schedule: [ cron: '0 0 * * 0' ]

jobs:
  discover-version-element:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # The ACCESS_TOKEN secret is defined at
          # https://github.com/Automattic/chat.a8c.com/settings/secrets/actions
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Discover latest version
        run: |
          curl -sL https://api.github.com/repos/vector-im/element-web/releases/latest | \
          jq -r ".tag_name" > latest-versions/element

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")

      - name: Assign version to environment variable
        if: steps.git-check.outputs.modified == 'true'
        run: echo 'ELEMENT_VERSION='$(cat latest-versions/element) >> $GITHUB_ENV

      - name: Commit latest version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Team Orbit'
          git config --global user.email 'orbit-matrix@automattic.com'
          git pull
          git add .
          git commit -m "Set Element latest version to ${{ env.ELEMENT_VERSION }}"
          git push

  discover-version-matrix-to:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # The ACCESS_TOKEN secret is defined at
          # https://github.com/Automattic/chat.a8c.com/settings/secrets/actions
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Discover latest version
        run: |
          curl -sL https://api.github.com/repos/Automattic/matrix.to/releases/latest | \
          jq -r ".tag_name" > latest-versions/matrix.to

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")

      - name: Assign version to environment variable
        if: steps.git-check.outputs.modified == 'true'
        run: echo 'MATRIX_TO_VERSION='$(cat latest-versions/matrix.to) >> $GITHUB_ENV

      - name: Commit latest version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Team Orbit'
          git config --global user.email 'orbit-matrix@automattic.com'
          git pull
          git add .
          git commit -m "Set matrix.to latest version to ${{ env.MATRIX_TO_VERSION }}"
          git push
